name: Create Release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install # Or use yarn if you prefer

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts # Match the artifact name from build.yml
          path: dist # Replace with the path where you want to download the artifacts

      - name: Run Semantic Release
        run: npx semantic-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/* # Replace with the path to your release files
        env:
          GITHUB_TOKEN: ${{ secrets.PT_GITHUB_TOKEN }}
